# Generated by Django 3.2.5 on 2021-08-21 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210821_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentupdate',
            name='image_url',
        ),
    ]
