# Generated by Django 3.2.5 on 2021-08-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_recentupdate_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentupdate',
            name='image_url',
            field=models.CharField(default='https://picsum.photos/600', max_length=140),
        ),
    ]
