# Generated by Django 3.2.5 on 2021-08-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_recentupdate_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_url',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='recentupdate',
            name='image_url',
            field=models.CharField(default='', max_length=140),
        ),
    ]
